global:
  scrape_interval: 15s #Intervalo de recoleccion de metricas

scrape_configs:
  - job_name: 'node-app' # Nombre del trabajo para identificar las metricas de la aplicación
    static_configs:
      - targets: ['app:3001'] # Objetivo: se corre la app en el contenedor "app" en el puerto 3001